Fix flake update

diff --git a/.github/actions/nix-update-flake/action.yml b/.github/actions/nix-update-flake/action.yml
--- a/.github/actions/nix-update-flake/action.yml
+++ b/.github/actions/nix-update-flake/action.yml
@@ -6,10 +6,6 @@ inputs:
   project_dir:
     description: Directory containing flake.nix
     required: true
-  update_lock_file:
-    description: "Whether to update the flakes' lock files before checking"
-    required: false
-    default: "false"
 
 runs:
   using: composite
@@ -18,23 +14,10 @@ runs:
       shell: bash
       working-directory: ${{ inputs.project_dir }}
       env:
-        UPDATE_LOCK_FILE: ${{ inputs.update_lock_file }}
         NIX_CONFIG: "experimental-features = nix-command flakes"
       run: |
         set -euo pipefail
-        
-        echo "→ Checking flake in $(pwd)"
-        
-        if [ "$UPDATE_LOCK_FILE" == "true" ]; then
-            if ! nix flake update; then
-                echo "  ✗ failed to update lock file"
-                exit 1
-            fi
-        fi
-        
-        if nix flake check --quiet --no-update-lock-file >/dev/null; then
-            echo "  ✓ Flake passed check"
-        else
-            echo "  ✗ Flake failed check"
+        if ! nix flake update; then
+            echo "  ✗ failed to update lock file"
             exit 1
         fi
